"""
upload_to_supabase.py
=====================
Fills the four existing Supabase tables from pipeline CSV outputs.

Tables filled:
  states           ← VT_scores_final.csv
  vt_history       ← VT_scores_final.csv  (year=2022 snapshot)
  carbon_relations ← fine_claims.csv       (relation_type='fine',      status='fine_pending')
                   ← attribution_network.csv (relation_type='transport', status='neutral'/'fine_pending')
  projects         ← not generated by pipeline; skipped (fill manually)

Setup:
  pip install supabase python-dotenv
  Create a .env file:
    SUPABASE_URL=https://xxxx.supabase.co
    SUPABASE_KEY=your-service-role-key

Run:
  python upload_to_supabase.py
"""

import os
import sys
import math
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from supabase import create_client, Client

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

load_dotenv()

SUPABASE_URL: str = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY: str = os.environ.get("SUPABASE_KEY", "")  # must be service-role key

if not SUPABASE_URL or not SUPABASE_KEY:
    sys.exit(
        "ERROR: Set SUPABASE_URL and SUPABASE_KEY in your environment or .env file.\n"
        "Use the service-role key (not the anon key) so writes are allowed."
    )

# Folder where pipeline writes its CSVs (outputs/ next to the pipeline script)
OUTPUT_DIR = Path(__file__).resolve().parent / "outputs"

# ---------------------------------------------------------------------------
# Pipeline constants reused here
# ---------------------------------------------------------------------------

STATE_AREA_KM2 = {
    "Andhra Pradesh": 162975, "Arunachal Pradesh": 83743, "Assam": 78438,
    "Bihar": 94163, "Chhattisgarh": 135192, "Delhi": 1484, "Goa": 3702,
    "Gujarat": 196024, "Haryana": 44212, "Himachal Pradesh": 55673,
    "Jharkhand": 79716, "Karnataka": 191791, "Kerala": 38852,
    "Madhya Pradesh": 308252, "Maharashtra": 307713, "Manipur": 22327,
    "Meghalaya": 22429, "Mizoram": 21081, "Nagaland": 16579, "Odisha": 155707,
    "Punjab": 50362, "Rajasthan": 342239, "Sikkim": 7096, "Tamil Nadu": 130058,
    "Telangana": 112077, "Tripura": 10486, "Uttarakhand": 53483,
    "Uttar Pradesh": 240928, "West Bengal": 88752,
}

ECOSYSTEM_LABEL = {"F": "forest", "I": "industrial", "M": "mixed"}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_csv(filename: str) -> pd.DataFrame:
    path = OUTPUT_DIR / filename
    if not path.exists():
        print(f"  [SKIP] {filename} not found at {path}")
        return pd.DataFrame()
    df = pd.read_csv(path)
    print(f"  [OK]   {filename}  ({len(df)} rows)")
    return df


def clean(val):
    """Replace NaN / inf with None so Supabase (JSON) accepts the payload."""
    if val is None:
        return None
    try:
        f = float(val)
        if math.isnan(f) or math.isinf(f):
            return None
    except (TypeError, ValueError):
        pass
    return val


def sanitise(records: list[dict]) -> list[dict]:
    return [{k: clean(v) for k, v in row.items()} for row in records]


def upsert(supabase: Client, table: str, rows: list[dict], chunk: int = 100):
    if not rows:
        print(f"  [SKIP] {table}: nothing to upsert")
        return
    total = len(rows)
    done = 0
    for start in range(0, total, chunk):
        batch = rows[start : start + chunk]
        supabase.table(table).upsert(batch).execute()
        done += len(batch)
        print(f"  {table}: {done}/{total}", end="\r")
    print(f"  [DONE] {table}: {total} rows upserted          ")


# ---------------------------------------------------------------------------
# Table builders
# ---------------------------------------------------------------------------

def build_states(vt_df: pd.DataFrame) -> list[dict]:
    """
    states schema:
      name text unique not null
      vt_balance numeric          <- VT_score
      archetype text              <- F / I / M
      ecosystem text              <- forest / industrial / mixed
      area_km2 numeric
      rank integer                <- rank by VT_score descending
    """
    df = vt_df[["state", "VT_score", "archetype"]].copy()
    df = df.sort_values("VT_score", ascending=False).reset_index(drop=True)
    df["rank"] = df.index + 1

    rows = []
    for _, r in df.iterrows():
        rows.append({
            "name":       r["state"],
            "vt_balance": round(float(r["VT_score"]), 4),
            "archetype":  r["archetype"],
            "ecosystem":  ECOSYSTEM_LABEL.get(r["archetype"], "mixed"),
            "area_km2":   STATE_AREA_KM2.get(r["state"]),
            "rank":       int(r["rank"]),
        })
    return sanitise(rows)


def build_vt_history(vt_df: pd.DataFrame, id_map: dict) -> list[dict]:
    """
    vt_history schema:
      state_id uuid references states(id)
      year integer not null
      vt_score numeric not null
      note text
    """
    rows = []
    for _, r in vt_df.iterrows():
        sid = id_map.get(r["state"])
        if not sid:
            print(f"    [WARN] No UUID for '{r['state']}' — skipping vt_history row")
            continue
        rows.append({
            "state_id": sid,
            "year":     2022,
            "vt_score": round(float(r["VT_score"]), 4),
            "note": (
                f"archetype={r['archetype']}; "
                f"emission_2022={round(float(r['emission_2022_mt']), 4)} MT; "
                f"absorption={round(float(r['absorption_mt']), 4)} MT; "
                f"effort_multiplier={round(float(r['effort_multiplier']), 4)}"
            ),
        })
    return sanitise(rows)


def build_carbon_relations_from_claims(
    claims_df: pd.DataFrame, id_map: dict
) -> list[dict]:
    """
    fine_claims.csv -> carbon_relations
      source_state_id <- defendant_state  (the polluter)
      target_state_id <- claimant_state   (the harmed state)
      relation_type   = 'fine'
      vt_impact       <- fine_vt_points   (penalty VT units)
      status          = 'fine_pending'    (valid per schema check constraint)
      period          = '2022'
    """
    rows = []
    for _, r in claims_df.iterrows():
        src = id_map.get(r["defendant_state"])
        tgt = id_map.get(r["claimant_state"])
        if not src or not tgt:
            print(f"    [WARN] Missing UUID for fine claim "
                  f"'{r['defendant_state']}' -> '{r['claimant_state']}' — skipping")
            continue
        rows.append({
            "source_state_id": src,
            "target_state_id": tgt,
            "relation_type":   "fine",
            "vt_impact":       round(float(r["fine_vt_points"]), 2),
            "status":          "fine_pending",
            "period":          "2022",
        })
    return sanitise(rows)


def build_carbon_relations_from_attribution(
    attr_df: pd.DataFrame, id_map: dict
) -> list[dict]:
    """
    attribution_network.csv -> carbon_relations
    Each bilateral pair becomes one row using net_aggressor as source.

    Columns used:
      net_aggressor, net_victim, net_magnitude_mt,
      fine_eligible_A_to_B, fine_eligible_B_to_A

    relation_type = 'transport'
    vt_impact     = net_magnitude_mt (net MT transported between the pair)
    status:
      'fine_pending' if either direction is fine-eligible
      'neutral'      otherwise
    period = '2022'
    """
    rows = []
    for _, r in attr_df.iterrows():
        aggressor = r.get("net_aggressor", "")
        victim    = r.get("net_victim", "")

        # Skip balanced pairs — no clear directional source/target
        if aggressor == "balanced" or victim == "balanced":
            continue

        src = id_map.get(aggressor)
        tgt = id_map.get(victim)
        if not src or not tgt:
            print(f"    [WARN] Missing UUID for attribution "
                  f"'{aggressor}' -> '{victim}' — skipping")
            continue

        fine_eligible = (
            bool(r.get("fine_eligible_A_to_B", False))
            or bool(r.get("fine_eligible_B_to_A", False))
        )

        rows.append({
            "source_state_id": src,
            "target_state_id": tgt,
            "relation_type":   "transport",
            "vt_impact":       round(float(r["net_magnitude_mt"]), 6),
            "status":          "fine_pending" if fine_eligible else "neutral",
            "period":          "2022",
        })
    return sanitise(rows)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("\n=== Supabase Upload ===\n")
    print(f"Reading CSVs from: {OUTPUT_DIR}\n")

    vt_df     = load_csv("VT_scores_final.csv")
    claims_df = load_csv("fine_claims.csv")
    attr_df   = load_csv("attribution_network.csv")
    print()

    if vt_df.empty:
        sys.exit("VT_scores_final.csv is required. Run the pipeline first.")

    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    print("Connected to Supabase.\n")

    # ------------------------------------------------------------------
    # 1. states
    # ------------------------------------------------------------------
    print("Step 1 — states")
    upsert(supabase, "states", build_states(vt_df))

    # Fetch back UUIDs Supabase assigned — needed for FK columns below
    result = supabase.table("states").select("id, name").execute()
    id_map: dict[str, str] = {row["name"]: row["id"] for row in result.data}
    print(f"  Retrieved {len(id_map)} state UUIDs.\n")

    # ------------------------------------------------------------------
    # 2. vt_history
    # ------------------------------------------------------------------
    print("Step 2 — vt_history")
    upsert(supabase, "vt_history", build_vt_history(vt_df, id_map))
    print()

    # ------------------------------------------------------------------
    # 3. carbon_relations  (fine claims + transport attribution)
    # ------------------------------------------------------------------
    print("Step 3 — carbon_relations")

    cr_rows: list[dict] = []

    if not claims_df.empty:
        fine_rows = build_carbon_relations_from_claims(claims_df, id_map)
        print(f"  fine_claims      -> {len(fine_rows)} rows")
        cr_rows.extend(fine_rows)
    else:
        print("  fine_claims.csv empty — no fine rows")

    if not attr_df.empty:
        transport_rows = build_carbon_relations_from_attribution(attr_df, id_map)
        print(f"  attribution_network -> {len(transport_rows)} rows")
        cr_rows.extend(transport_rows)
    else:
        print("  attribution_network.csv empty — no transport rows")

    upsert(supabase, "carbon_relations", cr_rows)
    print()

    # ------------------------------------------------------------------
    # 4. projects — pipeline doesn't generate these
    # ------------------------------------------------------------------
    print("Step 4 — projects")
    print("  [SKIP] The pipeline doesn't generate project data.")
    print("         Add rows manually via Supabase dashboard or a separate script.\n")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print("=== Done ===")
    print(f"  states           : {len(build_states(vt_df))} rows")
    print(f"  vt_history       : {len(build_vt_history(vt_df, id_map))} rows")
    print(f"  carbon_relations : {len(cr_rows)} rows")
    print(f"  projects         : skipped")


if __name__ == "__main__":
    main()